### ISSUE TITLE
Prometheus Random Test failure

### ISSUE THREAD

**Issue by juanpedromoreno** [higherkindness/mu#168]
After upgrading from Prometheus `0.1.0` to `0.2.0`, a new test failure is happening randomly:

```bash
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:517)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:356)
	at freestyle.rpc.internal.MonixAdapters$$anon$4$$anon$1.onComplete(MonixAdapters.scala:66)
	at monix.reactive.internal.builders.TaskAsObservable$$anon$1.onSuccess(TaskAsObservable.scala:32)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:167)
	at monix.eval.internal.TaskRunLoop$RestartCallback.onSuccess(TaskRunLoop.scala:659)
	at monix.eval.Callback.apply(Callback.scala:58)
	at monix.eval.instances.CatsAsyncForTask$$anonfun$async$1$$anonfun$apply$1.apply(CatsAsyncForTask.scala:38)
	at monix.eval.instances.CatsAsyncForTask$$anonfun$async$1$$anonfun$apply$1.apply(CatsAsyncForTask.scala:38)
	at cats.effect.internals.IOPlatform$$anonfun$onceOnly$1.apply(IOPlatform.scala:75)
	at cats.effect.internals.IOPlatform$$anonfun$onceOnly$1.apply(IOPlatform.scala:75)
	at monix.eval.internal.TaskConversions$$anonfun$toIO$1$$anonfun$apply$1$$anonfun$apply$2.apply(TaskConversions.scala:43)
	at monix.eval.internal.TaskConversions$$anonfun$toIO$1$$anonfun$apply$1$$anonfun$apply$2.apply(TaskConversions.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] - should work for client streaming RPC metrics *** FAILED ***m
[info]   0 was not equal to 1 (BaseMonitorServerInterceptorTests.scala:97)
```

**Comment by juanpedromoreno** [comment]
Is this fixed now? Could we close it?

**Comment by fedefernandez** [comment]
No, indeed it appears more frequently in local

**Comment by fedefernandez** [comment]
Let's close this for now. It doesn't look it's happening again.
