### ISSUE TITLE
Monix bidirectional-streaming random test failure

### ISSUE THREAD

**Issue by L-Lavigne** [higherkindness/mu#282]
Bidirectional-streaming Monix/Observable tests intermittently fail on Travis. Unlike #164, this happens as a thrown exception rather than an empty result. It is also somewhat dependent on test ordering and the status of the channel, since ignoring/canceling the first bidi test has been enough to avoid the error in all three (bidi, bidi with schema, run monadically). So it might be possible to avoid this error by starting a new server before each test or using the in-process server, but we'd still want to find if/why bidirectional streaming can leave a  connection in an inconsistent state.

Sample output from https://travis-ci.org/frees-io/freestyle-rpc/jobs/385347314: 

```
[info] frees-rpc client with compression
[info] - should be able to run unary services
[info] - should be able to run unary services with avro schema
[info] - should be able to run server streaming services
[info] - should be able to run client streaming services
[info] - should be able to run client bidirectional streaming services
[info] - should be able to run client bidirectional streaming services with avro schema
May 29, 2018 7:07:49 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@8513dc5
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:172)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:358)
	at freestyle.rpc.internal.MonixAdapters$$anon$4$$anon$1.onComplete(MonixAdapters.scala:66)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber.monix$reactive$internal$operators$ConcatMapObservable$ConcatMapSubscriber$$sendOnComplete(ConcatMapObservable.scala:333)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber.signalFinish(ConcatMapObservable.scala:302)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber.onComplete(ConcatMapObservable.scala:324)
	at monix.reactive.subjects.PublishSubject.sendOnCompleteOrError(PublishSubject.scala:176)
	at monix.reactive.subjects.PublishSubject.onComplete(PublishSubject.scala:108)
	at freestyle.rpc.internal.server.package$$anon$1.onComplete(package.scala:41)
	at freestyle.rpc.internal.MonixAdapters$$anon$2$$anon$5.onCompleted(MonixAdapters.scala:40)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onHalfClose(ServerCalls.java:259)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:698)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: call is closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:129)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:341)
	at freestyle.rpc.internal.MonixAdapters$$anon$4$$anon$1.onNext(MonixAdapters.scala:69)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber$$anon$1.onNext(ConcatMapObservable.scala:140)
	at monix.reactive.internal.builders.IteratorAsObservable.monix$reactive$internal$builders$IteratorAsObservable$$fastLoop(IteratorAsObservable.scala:164)
	at monix.reactive.internal.builders.IteratorAsObservable$$anonfun$reschedule$1.apply(IteratorAsObservable.scala:109)
	at monix.reactive.internal.builders.IteratorAsObservable$$anonfun$reschedule$1.apply(IteratorAsObservable.scala:104)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] - should be able to run rpc services monadically *** FAILED ***
[info]   io.grpc.StatusRuntimeException: INTERNAL: Failed to frame message
[info]   at io.grpc.Status.asRuntimeException(Status.java:526)
[info]   at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 182),INTERNAL: Failed to frame message,RPCTests,freestyle.rpc.protocol.RPCTests,Some(freestyle.rpc.protocol.RPCTests),frees-rpc client with compression should be able to run rpc services monadically,be able to run rpc services monadically,Vector(),Some(io.grpc.StatusRuntimeException: INTERNAL: Failed to frame message),Some(349),Some(IndentedText(- should be able to run rpc services monadically,should be able to run rpc services monadically,1)),Some(SeeStackDepthException),Some(freestyle.rpc.protocol.RPCTests),None,pool-1-thread-1-ScalaTest-running-RPCTests,1527620869501).
java.io.NotSerializableException: io.grpc.Status
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.lang.Thread.run(Thread.java:748)
[info]   at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:37)
[info]   at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[info]   at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[info]   at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
[info]   at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:37)
[info]   at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[info]   at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[info]   at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
[info]   ...
```

**Comment by juanpedromoreno** [comment]
Is this fixed now? Couls we close it?

**Comment by fedefernandez** [comment]
Yes
