### ISSUE TITLE
Improvements to Mu docs for easier developer on boarding

### ISSUE THREAD

**Issue by rlmark** [higherkindness/mu#474]
Based on the Mu documentation, I spun up the quickstart hello world app. Some findings:

1. Mu uses Cats 0.x.x and I was using Cats 1.x.x. I don’t believe the version of Cats that Mu relies on was referenced explicitly in the docs. If you are using Cats 1.x.x in your project with Mu, you might see some odd and difficult to debug errors at runtime. (Though, it should be noted, the service error is easier to understand than the client error)

Server error: 
```
Exception in thread "grpc-default-executor-0" java.lang.NoSuchMethodError: cats.effect.Effect.runAsync(Ljava/lang/Object;Lscala/Function1;)Lcats/effect/IO;
	at mu.rpc.internal.server.monixCalls$$anon$1.invoke(monixCalls.scala:44)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Client error: 
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Proposal: We don’t want to propagate the service error to the client (generally unsafe, too much info,) so we should at least add a statement about the current version of Cats supported in the docs so that new users of Mu on the cats 1.x.x ecosystem don’t get confused. As for GRPC returning something other than a `StatusRuntimeException: UNKNOWN` to the client, I’m not sure if that is within our purview. 
Other option: Upgrade Cats version of Mu and bump Mu’s major version. Publish a little matrix of mu version to cats version like some of the Typelevel projects do. 

2. The documented necessity of the scalamacros paradise compiler plugin is found on the GitHub page, not in the actual microsite docs. I propose we also add that on the home page under “Installation”. Fun note: SBT build behavior (my version is 1.2.6) changes based on where you put the scalamacros paradise plugin. You must put it after your library dependencies block for complicated SBT reasons.

**Comment by rlmark** [comment]
Closing this as relevant changes were made and merged in a few days ago in #475. Sorry for the delay!
